Luis learn more
RochX/hornethq-2.0-integrated pull request #31
Opened 2023-11-14 23:35 UTC by LuisLizardo

2023-11-14 23:45 UTC, RochX requested changes
I like the idea of the randomized carousel and the images used, but some courses that shouldn't be put on there are, such as SIP courses and Study Abroad "courses."

I also prefer @harshsepi0l's course details page over the the learn more page here.

@LuisLizardo you should talk to @harshsepi0l about this before the demo tomorrow.

This is just a visual change, so it won't effect my practice of the demo.

2023-11-14 23:56 UTC, harshsepi0l reviewed
Yeah there's a lot of stuff in here that can cause some changes to how the page is going to work. I can look it over with Luis tomorrow before the demo.

2023-11-14 23:56 UTC, harshsepi0l commented on src/components/Carousel/Carousel.jsx
> -              ...new Set(
Need to have this or the faculty names display multiple times

2023-11-14 23:59 UTC, harshsepi0l commented on src/components/Carousel/Carousel.jsx
> -const Carousel = ({ onDataPassed }) => {
I need this const to be in there so the data from here gets passed to display.

2023-11-15 13:48 UTC, harshsepi0l commented
Finished merging a different pull request in place of this. so closing it now.

2023-11-15 13:48 UTC, closed without merging